// Static file served by the web itself (generated by scripts/export_web_scenarios.py).
import { request, toApiError } from './errors'
import type { ScenarioFile } from './types'

export async function loadScenarios(): Promise<ScenarioFile> {
  const resp = await request('/scenarios.json')
  if (!resp.ok) throw await toApiError(resp)
  return (await resp.json()) as ScenarioFile
}
